apiVersion: apps/v1
kind: Deployment
metadata:
  name: baolm-capstone
  labels:
    app: baolm-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baolm-capstone
  template:
    metadata:
      labels:
        app: baolm-capstone
    spec:
      containers:
        - name: baolm-capstone
          image: hub.docker.com/r/minhbao03/baolmcapstone
          imagePullPolicy: Always
          ports:
            - name: app
              containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: baolm-capstone-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      name: capstone
      protocol: TCP
  selector:
    app: baolm-capstone