apiVersion: apps/v1
kind: Deployment
metadata:
  name: baolm-capstone1
  labels:
    app: baolm-capstone1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baolm-capstone1
  template:
    metadata:
      labels:
        app: baolm-capstone1
    spec:
      containers:
        - name: baolm-capstone1
          image: docker.io/minhbao03/baolmcapstone
          imagePullPolicy: Always
          ports:
            - name: app
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: baolm-capstone1-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      name: capstone
      protocol: TCP
  selector:
    app: baolm-capstone1