version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

jobs:
  init-dockerfile:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv .devops
            source .devops/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./.devops
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            source .devops/bin/activate
            make lint
            

  build-push-docker-images:
    docker:
      - image: "cimg/python:3.10"
        user: root
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17
          docker_layer_caching: false
      - run:
          name: build push to docker hub
          command: |
            docker build . -t baolmcapstone:latest
            docker tag baolm minhba03/baolmcapstone:latest
            docker push minhba03/baolmcapstone:latest
  
  create-aws-cluster:
    docker:
      - image: "cimg/python:3.10"
    steps:
      - checkout
      - aws-eks/create-cluster:
          cluster-name: baolm-capstone
          aws-region: us-east-1
          node-type: t3.medium
          nodes-min: 1
          nodes-max: 3

  create-deployment:
    docker:
      - image: "cimg/python:3.10"
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: baolm-capstone
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: infrastructure.yaml
          show-kubectl-command: true
      - kubernetes/create-or-update-resource:
          resource-file-path: eks.yaml
          show-kubectl-command: true
      - run:
          command: |
            kubectl get nodes -o wide
            kubectl get all 
            kubectl get svc -o wide
            kubectl describe pods

workflows:
  deployment:
    jobs:
      - init-dockerfile
      - build-push-docker-images:
          requires:
            - "init-dockerfile"
      - create-aws-cluster:
          requires:
            - "init-dockerfile"
      - create-deployment:
          requires: [build-push-docker-images, create-aws-cluster]